spring:
  datasource:
    url: jdbc:mysql://db:3306/newtome?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true



  app:
    jwt:
      secret: ${JWT_SECRET}

  aws:
    s3:
      bucket: newtome-images-115944781330-us-east-1-an

  cdn:
    image-url: https://d3qyvu5wcarbxw.cloudfront.net