spring.application.name=newtome-api
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/newtome?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ricky123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
