spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

app.jwt.secret=lsdrgj89we45h9ygqoawepjngh0589q34hg0q3459jgh90[345aehjg0[we95jgh0459[wj5
app.jwt.exp-minutes=60
